# Follow a user
POST http://localhost:3000/api/user/follow/602a74d13cda032d18c1d6f7
content-type: application/json
apiKey:bbe44b27f2ea4464a198c929c1adc49e

{
  "followedUserId": "602a78ef52790830bc4995f5" 
}

###

# Get user's followers 
GET http://localhost:3000/api/user/followers/602a78ef52790830bc4995f5
content-type: application/json
apiKey:bbe44b27f2ea4464a198c929c1adc49e


###



