# Save comment
POST http://localhost:3000/api/comment/saveComment
content-type: application/json
apiKey:bbe44b27f2ea4464a198c929c1adc49e


{
"writer": "6021103b43901419f434b13b", "postId":"uniquepostId", "content":"this is another one"
}

###